config/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, DetailView, ListView
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from busao.models import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'config.views.home', name='home'),
    # url(r'^config/', include('config.foo.urls')),


    url(r'^$', ListView.as_view(model=Cidade, template_name='home.html'), name='home'),
    url(r'^consulta/$', 'busao.views.consulta', name='consulta'),
    url(r'^consultalugar/$', 'busao.views.consulta_poltrona', name='proximo'),
    
    url(r'^identificar/$', 'cliente.views.identificar', name='identificar'),



    # url(r'^$', ListView.as_view(model=Cidade, template_name='home.html'), name='home'),
    # url(r'^consulta/$', 'busao.views.consulta', name='consulta'),
    # url(r'^consultalugar/$', 'busao.views.consulta_poltrona', name='proximo'),


    # url(r'^$', 'venda.views.vendas', name='home'),
    #url(r'^home$', TemplateView.as_view(template_name='home.html'), name='home'),
    #url(r'^consulta/$', TemplateView.as_view(template_name='consulta.html'), name='consulta'),
    # url(r'^consulta/$', 'venda.views.consulta', name='consulta'),

    #url(r'^iidentificar/$', TemplateView.as_view(template_name='identificar.html'), name='identificar'),
   
    url(r'^pagamento/$', TemplateView.as_view(template_name='pagamento.html'), name='pagamento'),
    
    #url(r'^detalhecompra/$', TemplateView.as_view(template_name='detalhecompra.html'), name='detalhecompra'),
    url(r'^cadastro/$', 'cliente.views.cliente_cadastro', name='cadastro'),
    url(r'^pagamento/$', 'cliente.views.cliente_cadastro', name='pagamento'),
    url(r'^detalhecompra/$', 'cliente.views.finalizar', name='detalhecompra'),

    #url(r'^home/$', 'cliente.views.consulta', name='consulta'),
    # url(r'^consulta/$', 'consulta.views.Consulta_Venda', name='comprar'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # # contato
    # url(r'^contato/send/$', 'app.contato.views.contato_send', name='contato_send'),

    # # project
    # url(r'^$', include('app.appsite.urls', namespace='appsite')),
    # # url(r'^exposicao/$', 'app.appsite.views.exposicao', name='exposicao'),
    # url(r'^exposicao/(?P<slug>[\w_-]+)/?$', DetailView.as_view(queryset=Exposicao.objects.filter(ativo=True),template_name='exposicao.html'), name='exposicao'),
    # url(r'^exposicao/(?P<slug>[\w_-]+)/fotos/$', ListView.as_view(model=ObraExposicao, template_name='exposicao_fotos.html'), name='fotos'),
    # url(r'^exposicao-nav/$', ListView.as_view(model=Exposicao, template_name='exposicao_nav.html'), name='exposicao_nav'),
)

busao/models.py
# -*- coding: utf-8 -*-
from django.db import models

class Cidade(models.Model):
    nome = models.CharField(max_length=255)
    
    class Meta:
        ordering = ('nome',)
        verbose_name = 'Cidade'
        verbose_name_plural = 'Cidades'

    def __unicode__(self):
        return self.nome

class Onibus(models.Model):
    saida = models.ForeignKey(Cidade,related_name='saida')
    destino = models.ForeignKey(Cidade,related_name='destino')
    horario_saida = models.TimeField()
    horario_volta = models.TimeField()
    data_saida = models.DateField('Data Saida', blank=True, null=False)
    data_volta = models.DateField('Data Volta', blank=True, null=False)
    valor = models.DecimalField('Valor',decimal_places=2, max_digits=8)

    def todas_poltronas(self):
        return Poltronas.objects.filter(onibus=self)

    def poltronas(self):
        return Poltronas.objects.filter(onibus=self, status=0).count()

    class Meta:
        ordering = ('data_saida',)
        verbose_name = 'Onibus'
        verbose_name_plural = 'Onibus'

class Poltronas(models.Model):
    
    STATUS = (
        (0, 'LIVRE'),
        (1, 'OCUPADO'),
    )

    onibus = models.ForeignKey(Onibus)
    numero = models.IntegerField(max_length=2)
    status = models.IntegerField(max_length=1, choices=STATUS, default=0)
    
    class Meta:
        ordering = ('numero',)
        verbose_name = 'Poltrona'
        verbose_name_plural = 'Poltronas'

    def __unicode__(self):
        return '{0}'.format(self.numero)

cliente/models.py
from django.db import models
from django.contrib.auth.models import User
   

class Cliente(models.Model):
     
    SEXOS = (
        ('I', '----'),
        ('M', 'Masculino'),
        ('F', 'Feminino'),
    )

    ESTADO_CIVIL = (
        (0, '----'),
        (1, 'Solteiro'),
        (2, 'Casado'),
    )

    ESTADO = (
        (0, '----'),
        (1, 'MINAS GERAIS'),
        (2, 'PARANA'),
        (3, 'BAHIA'),
        (4, 'GOIAS'),
        (4, 'SAO PAULO'),
    )

    CIDADES = (
        (0, '----'),
        (1, 'SAO PAULO'),
        (2, 'RIBEIRAO PRETO'),
        (3, 'ITAU'),
        (4, 'DELFINOPOLIS'),
        (5, 'SAO SEBASTIAO DO PARAISO'),
        (6, 'FRANCA'),
    )

    PAIS = (
        (1, 'BRASIL'),
    )

    user = models.OneToOneField(User, null=True, blank=True)
    ativo = models.BooleanField(default=True)
    cpf = models.CharField(max_length=11, unique=True)
    nome = models.CharField(max_length=100)
    data_nasc = models.DateField('Data de Nascimento', blank=True, null=False)
    sexo = models.CharField(max_length=1, choices=SEXOS, default='I')
    estado_civil = models.IntegerField(max_length=1, choices=ESTADO_CIVIL, default=0)
    telefone = models.CharField(max_length=13)
    celular = models.CharField(max_length=13)
    cep = models.CharField(max_length=8)
    estado = models.IntegerField(max_length=1, choices=ESTADO, default=0)
    cidade = models.IntegerField(max_length=1, choices=CIDADES, default=0)
    pais = models.IntegerField(max_length=1, choices=PAIS, default=1)
    bairro = models.CharField(max_length=100)
    endereco = models.CharField(max_length=100)
    numero = models.IntegerField(max_length=10)
    complemento = models.CharField(max_length=30)
    email = models.CharField(max_length=30)
    senha = models.CharField(max_length=8)
    confirmar_senha = models.CharField(max_length=8)
    

consulta/models.py
from django.db import models

# Create your models here.

class Destino(models.Model):
	cidadeDestino = models.CharField(max_length=100)
	dataDestino = models.DateField('data destino')
	hora_partida = models.CharField(max_length=5)
	hora_chegada = models.CharField(max_length=5)
	valor = models.DecimalField(max_digits=5, decimal_places=2)
	poltrona_livres = models.IntegerField(max_length=5)

consulta/forms.py
from django.forms import ModelForm
from models import Consulta

class ConsultaForm(ModelForm):
    class Meta:
        model = Consulta

consulta/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from models import *

def Consulta_Venda(request):

    #saida_cidade = request.POST.get('cidadeDestino')
    # consulta = Consulta_Venda.objects.filter(saida_cidade=cidadeDestino)

    viagens = Destino.objects.all()

    return render(request, 'home.html', {
        'viagens': viagens,
    })

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <!-- Google -->
    <meta name="verify-v1" content="/a2TCJq+UU7t+A1yqb767Ydcld61oru6YOSU4QEaVFc=" />
    <meta name="verify-v1" content="iTvEtW78UxLT54yMb0Jd1M+l/cTiAGT2Kp3ObNWNwFk=" />
    <!-- Formato -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <title>VENDAS DE PASSAGEM ONLINE</title>
    
    <!-- Descrição do site -->
    <meta name="description" content="SOS LINKS" >
    <meta name="keywords" content="SOS LINKS">
    
    <!-- Localização do site -->
    <meta http-equiv="Content-language" content="pt-BR">

    <!-- Icone do site -->
    <link Rel="Add Icon" Href="{{ STATIC_URL }}imgs/icone.png">
    <link Rel="Shortcut Icon" Href="{{ STATIC_URL }}imgs/icone.png">
    <link rel="Icon" href="{{ STATIC_URL }}imgs/icone.png" type="image/png">
    
    <!-- CSS do site -->
    <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css" type="text/css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/estilo.css" type="text/css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/reset.css" type="text/css">
    {% block css %}
    {% endblock %}

</head>
<body>    
<header>
<div id="box">
    <div id="logo">

    </div>

        <h1> HLPR TURISMO - LTDA</h1>
    </div>
</header>
    {% block menu %}{% include "menu.html" %}{% endblock %}
<div class="content">
    {% block content %}

{% endblock %}
</div>

 <footer>
    <div id="box">
        <p> Todos os direitos reservados - 2012 </p>
    </div>
</footer>
</body>
</html>

templates/cadastro.html
{% extends "base.html" %}

{% block css %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/cadastro.css" type="text/css">
{% endblock %}

{% block content %}
<div class="grid-cadastro">
 <form action="{% url cadastro %}" method="POST"> {% csrf_token %}
    <table cellspacing="10" align="center">
        <tr>
            <td>
                <label>{{ form.user.errors }}</label>
                <label>{{ form.cpf.errors }}</label>
                
                <label for="id_cpf">CPF</label>
                {{ form.cpf }}

            </td>
            <td colspan="2" class="nome">
                <label>{{ form.nome.errors }}</label>
                <label for="id_nome">Nome</label> <!-- style="width: 449px;" -->
                {{ form.nome }}
            </td>
            <td>

                <label>{{ form.data_nasc.errors }}</label>
                <label for="data_nasc">Data de Nascimento</label>
                {{ form.data_nasc }}
        </tr>

        <tr>
            <td>
                {{ form.id_sexo.errors }}
                <label for="id_sexo">Sexo</label>
                {{ form.sexo }}
            </td>
            <td>
                {{ form.id_estado_civil.errors }}
                <label for="id_estado_civil">Estado Civil</label>
                {{ form.estado_civil }}
            </td>
            <td>
                {{ form.cidade.errors }}
                <label>Cidade</label>
                {{ form.cidade }}
            </td>
            <td><label>CEP</label>
                {{ form.cep }}
<!--                 <input type="text" maxlength="10"/></td>
 -->        </tr>

        <tr>
            <td>
                {{ form.celular.errors }}
                <label>Celular</label>
                {{ form.celular }}
            </td>
            <td>
                {{ form.telefone.errors }}
                <label>Telefone</label>
                {{ form.telefone }}
            <td class="estado">
                {{ form.estado.errors }}
                <label>Estado</label> 
                {{ form.estado }} <!-- style="width: 274px;" -->
            </td>
            <td>
                {{ form.pais.errors }}
                <label>País</label>
                {{ form.pais }}
            </td>
        </tr>

        <tr>
            <td colspan="2" class="bairro"> 
                {{ form.bairro.errors }}
                <label>Bairro</label> <!-- style="width: 350px;" -->
                {{ form.bairro }}
            </td>
            <td colspan="2" class="endereco">
                {{ form.endereco.errors }}
                <label>Endereço</label><!-- style="width: 449px;" -->
                {{ form.endereco }}
            </td>
        </tr>

        <tr>
            <td>
                {{ form.numero.errors }}
                <label>Número</label>
                {{ form.numero }}
            </td>
            <td>
                {{ form.complemento.errors }}
                <label>Complemento</label>
                {{ form.complemento }}
            </td>
            <td colspan="2" class="email">
                {{ form.email.errors }}
                <label>Email</label> <!--  style="width: 449px;" -->
                {{ form.email }}
            </td>
        </tr>

        <tr>
            <td>
                {{ form.senha.errors }}
                <label>Senha</label>
                {{ form.senha }}
            </td>
            <td>
                {{ form.confirmar_senha.errors }}
                <label>Confirmar senha</label>
                {{ form.confirmar_senha}}
            </td>
        </tr>

        <tr>
            <td>
                {{ form.ativo.errors }}
                <label>Ativo</label>
                {{ form.ativo }}
            </td>
            <!-- <td>
                <label>User</label>
                {{ form.user }}
            </td> -->
            <td>
                 <input type="submit" value=" CADASTRAR " />
            </td>

            <td>{{ form.sucesso }}</td>
        </tr>
    </table>
</form>
</div>
{% endblock %}

templates/consulta.html
{% extends "base.html" %}
{% load url from future %}

{% block css %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/consulta.css" type="text/css">
{% endblock %}

{% block content %}
<div class="content-consulta">
	<div class="grid-bloco">
		{% if busao %}
		<form method="POST" action="/consultalugar/">
		{% csrf_token %}
    	<label class="cidade">
	    	<b>Saida</b> {{ busao.saida.nome }} - <b>Destino</b> {{ busao.destino.nome }} - 

	    	{% for onibus in onibus %}
	    	</b>{{ onibus.data_saida }} <b>
	    	{% endfor %}
    	</label>
	    <div class="tabela-resultado">
	        <table cellpadding="10">
	            <tr class="title">
	                <td><label>Selecionar</label></td>
	                <td><label>Partida</label></td>
	                <td><label>Chegada</label></td>
	                <td><label>Valor</label></td>
	                <td><label>Poltronas livres</label></td>
	            </tr>
				{% for onibus in onibus %}
	           	<tr class="resultado">
	                <td><input type="radio" name="r3" id="r3"/><input type="hidden" name="onibus" value="{{ onibus.id }}" /></td>
	                <td><label for="r3"> {% comment %} {{ onibus.data_saida }} {% endcomment %}{{ onibus.horario_saida }}</label></td>
	                <td><label for="r3">{% comment %}{{ onibus.data_volta }} - {% endcomment %}{{ onibus.horario_volta }}</label></td>
	                <td><label for="r3">{{ onibus.valor }}</label></td>
	                <td><label for="r3">{{ onibus.poltronas }}</label></td>
	            </tr>
    		 	{% endfor %}

	        
	        </table>
	       
		    </div>
		     <input type="submit" value="Proximo" style="margin-left: 200px; margin-top: 50px;"/> 
		</form>
		{% else %}
			Nenhum onibus para sua escolha
		{% endif %}
    </div>
</div>
{% endblock %}

templates/consultalugar.html
{% extends "base.html" %}

{% block css %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/consultalugar.css" type="text/css">
{% endblock %}

{% block content %}
<form method="POST" action="/identificar/">
    {% csrf_token %}

<div class="content-bus">
        <div class="grid-371 grid-date">
            <table border="0" cellpadding="5" cellspacing="5">
                <tr class="title">
                    <td class="data">Data</td>
                    <td>Serviço</td>
                    <td>Valor</td>
                </tr>

                <tr class="title-result">
                    <td class="data">{{ onibus.data_saida }} {% comment %}- {{ onibus.horario_saida }}{% endcomment %}</td>
                    <td>00015</td>
                    <td>R$ {{ onibus.valor }},00</td>
                </tr>
            </table>
        </div>

        <div class="grid-371 grid-destino">
            <table border="0" cellpadding="5" cellspacing="0">
                <tr class="title">
                    <td>Destino</td>
                </tr>

                <tr class="origem-local">
                    <td>Partida - {{ onibus.saida }} - {{ onibus.horario_saida }}</td>
                    <td>Chegada - {{ onibus.destino }} - {{ onibus.horario_volta }}</td>
                </tr>
            </table>
        </div>

        <div class="grid-371 grid-legend">
            <table border="0" cellpadding="5" cellspacing="5">
                <tr class="title">
                    <td colspan="2">Legenda</td>
                </tr>

                <tr class="view-legend">
                    <td><span class="cub1"></span> Livre</td>
                    <td><span class="cub2"></span> Ocupado</td>
                </tr>
            </table>
        </div>
      
        

        <div class="escolha-lugares">
            <div class="poltronas">

                <div style="float:left; width:701px; position: absolute; top: 30px; left: 90px">
        {% for p in onibus.todas_poltronas %}
        
        <div style=" width: 50px; height: 30px; padding-top: 9px; float:left; margin-left: 15px; margin-top: 30px;">
            <input type="checkbox" id="r{{ p.numero }}" name="r{{ p.numero }}" />
            <label for="r{{ p.numero }}" style="background-color:{% if p.status == 0 %}green{% else %}red{% endif %};">{{ p.numero }}</label>
        </div>
        {% endfor %}
        </div>
                <!-- <table border="0" cellpadding="7" cellspacing="0" class="lado-direito ">
                    <tr>
                        <td><input type="checkbox" id="r{{ p.numero }}" name="r{{ p.numero }}" /><label for="r01"  style="background-color:{% if p.status == 0 %}green{% else %}red{% endif %};">01</label></td>
                        <td><input type="checkbox" id="r05" name="r05"/>for="r{{ p.numero }}">{{ p.numero }}</label></td>
                        <td><input type="checkbox" id="r09" name="r09"/><label for="r09">09</label></td>
                        <td><input type="checkbox" id="r13" name="r13"/><label for="r13">13</label></td>
                        <td><input type="checkbox" id="r17" name="r17"/><label for="r17">17</label></td>
                        <td><input type="checkbox" id="r21" name="r21"/><label for="r21">21</label></td>
                        <td><input type="checkbox" id="r25" name="r25"/><label for="r25">25</label></td>
                        <td><input type="checkbox" id="r29" name="r29"/><label for="r29">29</label></td>
                        <td><input type="checkbox" id="r33" name="r33"/><label for="r33">33</label></td>
                        <td><input type="checkbox" id="r37" name="r37"/><label for="r37">37</label></td>
                    </tr>

                    <tr>
                        <td><input type="checkbox" id="r02" name="r02"/><label for="r02">02</label></td>
                        <td><input type="checkbox" id="r06" name="r06"/><label for="r06">06</label></td>
                        <td><input type="checkbox" id="r10" name="r10"/><label for="r10">10</label></td>
                        <td><input type="checkbox" id="r14" name="r14"/><label for="r14">14</label></td>
                        <td><input type="checkbox" id="r18" name="r18"/><label for="r18">18</label></td>
                        <td><input type="checkbox" id="r22" name="r22"/><label for="r22">22</label></td>
                        <td><input type="checkbox" id="r26" name="r26"/><label for="r26">26</label></td>
                        <td><input type="checkbox" id="r30" name="r30"/><label for="r30">30</label></td>
                        <td><input type="checkbox" id="r34" name="r34"/><label for="r34">34</label></td>
                        <td><input type="checkbox" id="r38" name="r38"/><label for="r38">38</label></td>
                    </tr>
                </table>

                <table border="0" cellpadding="7" cellspacing="0" class="lado-esquerdo">
                    <tr>
                        <td><input type="checkbox" id="r03" name="r03"/><label for="r03">03</label></td>
                        <td><input type="checkbox" id="r07" name="r07"/><label for="r07">07</label></td>
                        <td><input type="checkbox" id="r11" name="r11"/><label for="r11">11</label></td>
                        <td><input type="checkbox" id="r15" name="r15"/><label for="r15">15</label></td>
                        <td><input type="checkbox" id="r19" name="r19"/><label for="r19" 
                             style="background-color:{% if p.status == 0 %}green{% else %}red{% endif %};">19</label></td>
                        <td><input type="checkbox" id="r23" name="r23"/><label for="r23">23</label></td>
                        <td><input type="checkbox" id="r27" name="r27"/><label for="r27">27</label></td>
                        <td><input type="checkbox" id="r31" name="r31"/><label for="r31">31</label></td>
                        <td><input type="checkbox" id="r35" name="r35"/><label for="r35">35</label></td>
                        <td><input type="checkbox" id="r39" name="r39"/><label for="r39">39</label></td>
                    </tr>
                    <tr>
                        <td><input type="checkbox" id="r04" name="r04"/><label for="r04">04</label></td>
                        <td><input type="checkbox" id="r08" name="r08"/><label for="r08">08</label></td>
                        <td><input type="checkbox" id="r12" name="r12"/><label for="r12">12</label></td>
                        <td><input type="checkbox" id="r16" name="r16"/><label for="r16">16</label></td>
                        <td><input type="checkbox" id="r20" name="r20"/><label for="r20">20</label></td>
                        <td><input type="checkbox" id="r24" name="r24"/><label for="r24">24</label></td>
                        <td><input type="checkbox" id="r28" name="r28"/><label for="r28">28</label></td>
                        <td><input type="checkbox" id="r32" name="r32"/><label for="r32">32</label></td>
                        <td><input type="checkbox" id="r36" name="r36"/><label for="r36">36</label></td>
                        <td><input type="checkbox" id="r40" name="r40"/><label for="r40">40</label></td>
                    </tr>
                </table> -->
            </div>
                <input type="submit" name="avancar" value="PROXIMO" class="proximo"/>
        </div>
        
    </div>
    </form>

    {% endblock %}

templates/detalhecompra.html
{% extends "base.html" %}
{% load url from future %}

{% block css %}

<link rel="stylesheet" href="{{ STATIC_URL }}css/detalhecompra.css" type="text/css">

{% endblock %}

{% block content %}
<form>
	<div class="grid-detalhes">
		<p>COMPROVANTE DE PAGAMENTO</p><br>
		<p>================================================================</p>
		<p>PEDIDO: </p>
		<p>================================================================</p>
		<p>CLIENTE: </p>
		<p>CPF: </p>
		<p>================================================================</p>
		<p>SAIDA: </p>
		<p>DESTINO:</p>
		<p>HORARIO:</p>
		<p>DATA DE EMBARGUE:</p>
		<p>POLTRONA:</p>
		
		<br /><br />
		<p>================================================================</p>
		<p>FORMAS DE PAGAMENTO:  </p>
		<p>TOTAL:</p>
		<p>================================================================</p>
		<p>================================================================</p>
		
		<div class="text">
			<p>OBS.: IMPRIMA O COMPROVANTE E DIRIJA-SE AO TERMINAL RODOVIÁRIO NA DATA DE EMBARGUE E RETIRE SUA PASSAGEM.</p><br /><br />
			<p>OBRIGADO, BOA VIAGEM!</p>
		</div>


	<input type="button" name="imprimir" value="Imprimir" onclick="window.print();">
	</div>
</form>
{% endblock%}

templates/home.html
{% extends "base.html" %}
{% load url from future %}

{% block css %}

{% endblock %}

{% block content %}
<div id="box">
    <div class="consulta grid-900">
        <div class="mapa">
           <img src="{{ STATIC_URL }}imgs/map.png" alt="mapa"/>
        </div>

        <div class="form-consulta">
            <h2 class="title">CONSULTA A COMPRA DE PASSAGENS ONLINE</h2>
            <form method="POST" action="/consulta/">
                {% csrf_token %}
                <div class="input-ida">
                    <input type="radio" name="ida"/>
                    <label for="ida">ida e volta</label>
                </div>
                
                <div class="input-s-ida">
                    <input type="radio" name="sida"/>
                    <label for="sida">somente ida</label>
                </div>
                
                <div class="seleciona-destino">
                    <div class="saida">
                        <div class="left">
                            <label for="saida">saída</label>
                            <select name="saida">
                            {% for cidade in object_list %}
                                <option value="{{ cidade.id }}">{{ cidade.nome }}</option>
                            {% endfor %}
                            </select>
                           
                        </div>
                        <div class="right">
                            <label>data de saida</label>
                            <input type="text" name="data_saida" />
                        </div>
                    </div>

                    <div class="destino top">
                        <div class="left">
                            <label for="destino">destiono</label>
                            <select name="destino">
                            {% for cidade in object_list %}
                                <option value="{{ cidade.id }}">{{ cidade.nome }}</option>
                            {% endfor %}
                            </select>
                        </div>
                        <div class="right">
                            <label>data de destino</label>
                            <input type="text" name="data_destino" />
                        </div>                    
                    </div>
                    
                    <input type="submit" value="Comprar"/>  
                </div>
            </form>
        </div>
    </div>
    <div id="ofertas_mae">

            <p> > Qual é o seu destino?</p>
            <div id="oferta1">
                <p>Londres?</p>
            </div>

            <div id="oferta2">
                <p>Roma?</p>
            </div>

            <div id="oferta3">
                <p>Nova Iorque?</p>
            </div>
    </div>
</div>   

{% endblock %}

templates/identificar.html
{% extends "base.html" %}
{% load url from future %}

{% block css %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/identificar.css" type="text/css">
{% endblock %}

{% block content %}
<div class="content-consulta">
	<div class="grid-bloco">
    	<div class="grid-identificar">
        <div class="entrar">
            <h2>Entre com seu usuário para efetuar a compra.</h2>
            <div class="form">
                <div class="form-login">
                    <form action="#">
                        <label>CPF</label>
                        <input type="text" maxlength="11"/>
                        {% for id in identificar %}
                            {{ id.cpf }}
                        {% endfor %}
                        <label>SENHA</label>
                        <input type="password" />
                        <input type="submit" value="Entrar" class="login"/>
                    </form>
                </div>
            </div>
        </div>

        <div class="cadastrar">
            <h2>Cadastre um novo usuário.</h2>
            <div class="form">
                <div class="grid-cadastro">
                    <img src="{{ STATIC_URL }}imgs/icon.png" alt="Cadastrar" />
                    <a href="{% url "cadastro" %}" >Clique aqui para cadastrar.</a>
                </div>
            </div>
        </div>
    
    </div>
    </div>
</div>
{% endblock %}

templates/menu.html
{% load url from future %}
<div class="nav">
    <ul>
        <li><a href="{% url "home" %}">HOME</a></li>
        <li><a href="{% url "consulta" %}">SELECIONAR</a></li>
        <li><a href="{% url "identificar" %}">INDENTIFICAR-SE</a></li>
        <li><a href="#">EFETUAR PAGAMENTO</a></li>
        <li><a href="#">DETALHES DA COMPRA</a></li>
    </ul>
</div>

templates/pagamento.html
{% extends "base.html" %}
{% load url from future %}

{% block css %}

<link rel="stylesheet" href="{{ STATIC_URL }}css/detalhecompra.css" type="text/css">

{% endblock %}

{% block content %}
<div class="grid-detalhes">
<form method="POST" action="/detalhecompra/">
	 {% csrf_token %}
	<h2> FORMAS DE PAGAMENTO </h2>

	<p>
		<select>
			<option>CARTAO DE CREDITO</option>
			<option>BOLETO</option>
		</select>

	</p>

	<p>================================================================</p>

	<p>SAIDA:</p>
	<p>DESTINO:</p>
	<p>DATA SAIDA:</p>
	<p>POLTRONAS: {% for f in finalizar %}{{ f.numeroPoltrona }}{% endfor %}</p>
	<p>================================================================</p>
	<p><input type="submit" value="FINALIZAR PEDIDO" /></p>
	
</form>
</div>
{% endblock %}